### ISSUE TITLE
How to change font size?

### ISSUE THREAD

**Issue by EuAndreh** [tinga-dev/ti-ionic-segmented-control#4]
How can I change the `font-size` of a `ti-segmented-control-button`? I couldn't find a way how to select it in CSS.

**Comment by wxmerkt** [comment]
You can add it here: https://github.com/tinga-dev/ti-ionic-segmented-control/blob/master/dist/ti-segmented-control.js#L20

**Comment by EuAndreh** [comment]
Thanks =]
